permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Huaijin Chen    
  email: chaochancs@gmail.com
  link: http://huaijin.info
  weibo: http://weibo.com/huaijin
  github: http://github.com/huaijin-chen
  music: http://site.douban.com/huaijin

# 站点信息
title: Huaijin的博客
description: My personal blog
url: http://huaijin.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
#gavatar: /public/img/deer3.png
#favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-64600841-1
  url: huaijin.info

# disqus 设置
#disqus:
#  shortname: huaijin

#duoshuo:
#    short_name: huaijin


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
